namespace SemiStep.Core.Configuration;

public sealed record GridStyleOptions(
	GridStyleFonts Fonts,
	GridStyleLayout Layout,
	SelectionColors Selection,
	ChangedCellColors ChangedCells,
	DepthPalette ReadOnlyCells,
	DepthPalette DisabledCells,
	ExecutionPalette Execution,
	StatusBarStyle StatusBar,
	ValidationPanelStyle ValidationPanel,
	ChromeColors Chrome,
	GridOrientation Orientation)
{
	// Test-only fallback; the #000000 cell palettes are placeholders, never rendered in production.
	public static GridStyleOptions Default { get; } = new(
		Fonts: new GridStyleFonts(
			FontFamily: "",
			HeaderFontSize: 14,
			HeaderFontWeight: 700,
			HeaderItalic: false,
			CellFontSize: 12,
			CellFontWeight: 400,
			CellItalic: false),
		Layout: new GridStyleLayout(
			CellPaddingLeft: 6,
			CellPaddingTop: 4,
			CellPaddingRight: 6,
			CellPaddingBottom: 4,
			RowHeight: 28),
		Selection: new SelectionColors(
			Background: StyleColor.Parse("#CCE4F7"),
			Foreground: StyleColor.Parse("#202020")),
		ChangedCells: new ChangedCellColors(
			Changed: StyleColor.Parse("#FFCC80"),
			ChangedSelected: StyleColor.Parse("#EFD3A4")),
		ReadOnlyCells: new DepthPalette(
			Depth0: StyleColor.Parse("#000000"),
			Depth1: StyleColor.Parse("#000000"),
			Depth2: StyleColor.Parse("#000000"),
			Depth3: StyleColor.Parse("#000000"),
			Depth0Past: StyleColor.Parse("#000000"),
			Depth1Past: StyleColor.Parse("#000000"),
			Depth2Past: StyleColor.Parse("#000000"),
			Depth3Past: StyleColor.Parse("#000000"),
			Selected: StyleColor.Parse("#000000"),
			Foreground: StyleColor.Parse("#000000")),
		DisabledCells: new DepthPalette(
			Depth0: StyleColor.Parse("#000000"),
			Depth1: StyleColor.Parse("#000000"),
			Depth2: StyleColor.Parse("#000000"),
			Depth3: StyleColor.Parse("#000000"),
			Depth0Past: StyleColor.Parse("#000000"),
			Depth1Past: StyleColor.Parse("#000000"),
			Depth2Past: StyleColor.Parse("#000000"),
			Depth3Past: StyleColor.Parse("#000000"),
			Selected: StyleColor.Parse("#000000"),
			Foreground: StyleColor.Parse("#000000")),
		Execution: new ExecutionPalette(
			Depth0: StyleColor.Parse("#000000"),
			Depth1: StyleColor.Parse("#000000"),
			Depth2: StyleColor.Parse("#000000"),
			Depth3: StyleColor.Parse("#000000"),
			Depth0Past: StyleColor.Parse("#000000"),
			Depth1Past: StyleColor.Parse("#000000"),
			Depth2Past: StyleColor.Parse("#000000"),
			Depth3Past: StyleColor.Parse("#000000"),
			CurrentStepMarker: StyleColor.Parse("#000000")),
		StatusBar: new StatusBarStyle(
			Background: StyleColor.Parse("#F0F0F0"),
			Foreground: StyleColor.Parse("#000000"),
			Padding: 5,
			ItemSpacing: 10,
			FontSize: 12,
			Weight: 400,
			Italic: false,
			TimerLabelFontSize: 14,
			TimerLabelWeight: 400,
			TimerLabelItalic: false,
			TimerValueFontSize: 24,
			TimerValueWeight: 400,
			TimerValueItalic: false),
		ValidationPanel: new ValidationPanelStyle(
			Background: StyleColor.Parse("#FFFFFF"),
			Foreground: StyleColor.Parse("#000000"),
			ErrorColor: StyleColor.Parse("#D32F2F"),
			WarningColor: StyleColor.Parse("#F57C00"),
			MaxHeight: 100),
		Chrome: new ChromeColors(
			Info: StyleColor.Parse("#1976D2"),
			Connected: StyleColor.Parse("#44BB44"),
			Disconnected: StyleColor.Parse("#FF4444"),
			LocalMode: StyleColor.Parse("#6C707E"),
			Connecting: StyleColor.Parse("#FFAF0F"),
			PanelBackground: StyleColor.Parse("#F8F8F8"),
			PanelHeaderBackground: StyleColor.Parse("#EEEEEE"),
			SubtleBorder: StyleColor.Parse("#D0D0D0"),
			Separator: StyleColor.Parse("#C0C0C0"),
			SecondaryForeground: StyleColor.Parse("#888888"),
			GridBorder: StyleColor.Parse("#808080"),
			GridBackground: StyleColor.Parse("#FFFFFF"),
			HeaderForeground: StyleColor.Parse("#000000"),
			GridLine: StyleColor.Parse("#E0E0E0")),
		Orientation: GridOrientation.RowsAsSteps);
}
