namespace SemiStep.Core.Configuration;

public sealed record GridStyleOptions(
	int HeaderFontSize,
	int CellFontSize,
	double CellPaddingLeft,
	double CellPaddingTop,
	double CellPaddingRight,
	double CellPaddingBottom,
	double RowHeight,
	string SelectionBackgroundColor,
	string SelectionForegroundColor,
	string NormalForegroundColor,
	string EnabledCellNormalColor,
	string EnabledCellSelectedColor,
	string ReadonlyCellNormalColor,
	string ReadonlyCellSelectedColor,
	string DisabledCellNormalColor,
	string DisabledCellSelectedColor,
	string AlternatingRowBackgroundColor,
	string NormalRowBackgroundColor,
	double GridLineThickness,
	string GridLineColor,
	string StatusBarBackgroundColor,
	string StatusBarForegroundColor,
	double StatusBarPadding,
	double StatusBarItemSpacing,
	string ValidationPanelBackgroundColor,
	string ValidationPanelForegroundColor,
	string ValidationPanelErrorColor,
	string ValidationPanelWarningColor,
	double ValidationPanelMaxHeight,
	string ExecutionDepth0Color,
	string ExecutionDepth1Color,
	string ExecutionDepth2Color,
	string ExecutionDepth3Color,
	string ExecutionDepth0PastColor,
	string ExecutionDepth1PastColor,
	string ExecutionDepth2PastColor,
	string ExecutionDepth3PastColor,
	string ExecutionCurrentStepMarkerColor)
{
	/// <summary>
	/// Fallback configuration used for shape/wiring tests only. The `#000000` sentinel values on
	/// the execution palette are intentional placeholders — production runs load real colors via
	/// <c>GridStyleValidator</c> + <c>GridStyleMapper</c> and never observe these defaults.
	/// </summary>
	public static GridStyleOptions Default { get; } = new(
		HeaderFontSize: 14,
		CellFontSize: 12,
		CellPaddingLeft: 6,
		CellPaddingTop: 4,
		CellPaddingRight: 6,
		CellPaddingBottom: 4,
		RowHeight: 28,
		SelectionBackgroundColor: "#0078D7",
		SelectionForegroundColor: "#FFFFFF",
		NormalForegroundColor: "#000000",
		EnabledCellNormalColor: "#FFFFFF",
		EnabledCellSelectedColor: "#0078D7",
		ReadonlyCellNormalColor: "#F5F5F5",
		ReadonlyCellSelectedColor: "#5A9ED7",
		DisabledCellNormalColor: "#E0E0E0",
		DisabledCellSelectedColor: "#89B4D7",
		AlternatingRowBackgroundColor: "#FAFAFA",
		NormalRowBackgroundColor: "#FFFFFF",
		GridLineThickness: 1.0,
		GridLineColor: "#E0E0E0",
		StatusBarBackgroundColor: "#F0F0F0",
		StatusBarForegroundColor: "#000000",
		StatusBarPadding: 5,
		StatusBarItemSpacing: 10,
		ValidationPanelBackgroundColor: "#FFFFFF",
		ValidationPanelForegroundColor: "#000000",
		ValidationPanelErrorColor: "#D32F2F",
		ValidationPanelWarningColor: "#F57C00",
		ValidationPanelMaxHeight: 100,
		ExecutionDepth0Color: "#000000",
		ExecutionDepth1Color: "#000000",
		ExecutionDepth2Color: "#000000",
		ExecutionDepth3Color: "#000000",
		ExecutionDepth0PastColor: "#000000",
		ExecutionDepth1PastColor: "#000000",
		ExecutionDepth2PastColor: "#000000",
		ExecutionDepth3PastColor: "#000000",
		ExecutionCurrentStepMarkerColor: "#000000");
}
