<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit.v3"/>
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Avalonia.Headless"/>
    <PackageReference Include="Avalonia.Headless.XUnit"/>
    <PackageReference Include="FluentAssertions"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    <PackageReference Include="Serilog"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemiStep.Core\SemiStep.Core.csproj"/>
    <ProjectReference Include="..\SemiStep.UI\SemiStep.UI.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="YamlConfigs\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
