<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Semistep</AssemblyName>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>SemiStep.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia"/>
    <PackageReference Include="Avalonia.HarfBuzz"/>
    <PackageReference Include="Avalonia.Desktop"/>
    <PackageReference Include="Avalonia.Themes.Fluent"/>
    <PackageReference Include="ReactiveUI.Avalonia"/>
    <PackageReference Include="Avalonia.Controls.DataGrid"/>
    <PackageReference Include="Avalonia.Controls.ColorPicker"/>
    <PackageReference Include="Avalonia.Win32"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    <PackageReference Include="Microsoft.Extensions.Logging"/>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="Serilog.Extensions.Logging"/>
    <PackageReference Include="Serilog.Sinks.Console"/>
    <PackageReference Include="Serilog.Sinks.File"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemiStep.Core\SemiStep.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**"/>
    <AvaloniaResource Remove="Assets\**\*.md"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Dialogs\ErrorWindow.axaml.cs">
      <DependentUpon>ErrorWindow.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plc\PlcConflictDialog.axaml.cs">
      <DependentUpon>PlcConflictDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="ShutdownService\ExitConfirmationDialog.axaml.cs">
      <DependentUpon>ExitConfirmationDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="MessageService\MessagePanel.axaml.cs">
      <DependentUpon>MessagePanel.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="MainWindow\AppStatusBar.axaml.cs">
      <DependentUpon>AppStatusBar.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="MainWindow\RecipeMenuBar.axaml.cs">
      <DependentUpon>RecipeMenuBar.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="MainWindow\RecipeToolBar.axaml.cs">
      <DependentUpon>RecipeToolBar.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="StyleEditor\GridStyleEditorWindow.axaml.cs">
      <DependentUpon>GridStyleEditorWindow.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="StyleEditor\RestartPromptDialog.axaml.cs">
      <DependentUpon>RestartPromptDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
