<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CsvHelper"/>
    <PackageReference Include="FluentResults"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
    <PackageReference Include="S7netplus"/>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="System.IO.Hashing"/>
    <PackageReference Include="System.Reactive"/>
    <PackageReference Include="YamlDotNet"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SemiStep.Tests"/>
  </ItemGroup>

</Project>
